[package]
name = "kolchanov-dev/rdk"
description = "Roblox Development Kit (RDK)"
version = "0.1.0"
license = "MIT"
authors = ["Vadim Kolchanov <kolchanov.dev@gmail.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
repository = "https://github.com/kolchanov-dev/roblox-development-kit"